POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test",
    "number": "022-3131-223"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Wow"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "313-333-231"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "022-3131-223"
}